### ISSUE TITLE
Review and update documentation for resources

### ISSUE THREAD

**Issue by rfitzhugh** [rubrikinc/terraform-provider-rubrik#40]
Review and update documentation for specific resources:

* `assign_sla`
* `cluster_version`
* `configure_timezone`

Ensure that details are thorough and all attributes are documented.

**Comment by shamsway** [comment]
Added to certification branch in commit https://github.com/rubrikinc/terraform-provider-rubrik/commit/5a83df3764974df5d9c544c7600eb67d5bce8488
