### ISSUE TITLE
Update documentation to reflect Terraform 0.12 requirements

### ISSUE THREAD

**Issue by shamsway** [rubrikinc/terraform-provider-rubrik#44]
**Is your feature request related to a problem? Please describe.**

As we prepare this to be an official Terraform provider, this module will be upgraded to be compatible with Terraform 0.12. This means that there are some syntax changes that will need to be updated in the Quick Start and other docs. README.me also needs to be updated so end users are aware of version requirements. [https://www.terraform.io/upgrade-guides/0-12.html](https://www.terraform.io/upgrade-guides/0-12.html) contains information on syntax changes.

**Describe the solution you'd like**

* Update README.md
* Update Quick Start
* Update any other function examples.

**Describe alternatives you've considered**

n/a

**Comment by jaapbrasser** [comment]
Documentation updated and repo has been merged into terraform-providers org
