### ISSUE TITLE
Update documentation to follow terraform.io standard

### ISSUE THREAD

**Issue by shamsway** [rubrikinc/terraform-provider-rubrik#48]
**Is your feature request related to a problem? Please describe.**

Update documentation to follow terraform.io standard. Terraform providers host documentation under /website/docs, which is then pulled into the main Terraform website.

**Describe the solution you'd like**

Update our documentation and directory structure to follow the expected format.

**Describe alternatives you've considered**

N/A

**Comment by jaapbrasser** [comment]
Documentation updated and repo has been merged into terraform-providers org
