### ISSUE TITLE
Resolve unchecked errors from d.Get

### ISSUE THREAD

**Issue by shamsway** [rubrikinc/terraform-provider-rubrik#49]
**Is your feature request related to a problem? Please describe.**

[d.Set](https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceData.Set) returns an [error](https://godoc.org/builtin#error), but there are many cases where the error is not checked. These errors must be checked to be included as an official provider.

**Describe the solution you'd like**

Update any code using d.Get to check that the error != nil, and if so, surface the error

**Describe alternatives you've considered**

n/a

**Additional context**

[https://github.com/kisielk/errcheck](https://github.com/kisielk/errcheck) can be used to find instances of unchecked errors. more info: [https://stackoverflow.com/questions/43898074/is-there-a-way-to-find-not-handled-errors-in-go-code](https://stackoverflow.com/questions/43898074/is-there-a-way-to-find-not-handled-errors-in-go-code)

**Comment by shamsway** [comment]
Looked through some other providers and they don't appear to be following this strictly, so this issue needs some additional research.

**Comment by jaapbrasser** [comment]
I looked at how we want to handle this, but from what I've seen other providers have not implemented error handling for these calls.

In which scenarios would this kind of error handling benefit us? I have not run into cases where d.get failed on me as of yet.

**Comment by shamsway** [comment]
There was a script in some of the other Terraform repos that was looking for unchecked errors, so I was afraid it was going to be a requirement to pass a CI pipeline. After doing more digging it looks like it's not as big of an issue as I first thought. I think we can close this issue if you agree @jaapbrasser

**Comment by jaapbrasser** [comment]
I've taken another look at this and decided that this won't add a lot of value if we implement this. We can reopen this issue if we think otherwise in the future.
