### ISSUE TITLE
Issues Building Latest Release

### ISSUE THREAD

**Issue by james-crowley** [rubrikinc/terraform-provider-rubrik#73]
**Expected Behavior**

When building the latest release I expect the code to compile and produce a binary.

**Current Behavior**

When building the latest release, `v1.0.4`, the build fails.

**Failure Information (for bugs)**

Here is the output I get when building the release:

```
main.go:5:2: cannot find package "github.com/rubrikinc/rubrik-provider-for-terraform/rubrikcdm" in any of:
	/go/src/github.com/rubrikinc/terraform-provider-rubrik/vendor/github.com/rubrikinc/rubrik-provider-for-terraform/rubrikcdm (vendor tree)
	/usr/local/go/src/github.com/rubrikinc/rubrik-provider-for-terraform/rubrikcdm (from $GOROOT)
	/go/src/github.com/rubrikinc/rubrik-provider-for-terraform/rubrikcdm (from $GOPATH)
```

**Steps to Reproduce**

1. Download the the latest release and extract it.
2. cd /go/src/github.com//rubrikinc/terraform-provider-rubrik/
3. go build -ldflags '-d -s -w'

**Other**
It seems like this error does not happen when cloning and building from master. Although when building from master the binary name is incorrect. The binary name is `rubrik-provider-for-terraform`, which breaks the standards of terraform providers. It should be `terraform-provider-rubrik`.

@jaapbrasser I see a couple PRs open about pulling back the release from Terraform. Are you planning on re-releasing a new version of the provider soonish?

**Comment by DamaniN** [comment]
Fixed by #76
